Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.network(:forwarded_port, guest: 5001, host: 5001)
    config.vm.network(:forwarded_port, guest: 5002, host: 5002)

    config.vm.provider(:virtualbox) do |vb|
        vb.name = "ubuntu2004"
    end

    config.vm.provision(:file, source: ".", destination: "~/Lab5")
    config.vm.provision(:shell, privileged: false, path: "linux-start.sh")
    config.vm.provision(:shell, privileged: false, path: "linux-start-lab.sh", run: :always)
end