services:
    nginx:
        build:
            dockerfile: Nginx\Dockerfile
        ports:
            - 5001:5001
            - 5002:5002
            - 5003:5003
        depends_on:
            - identity_server
            - app
            - api

    identity_server:
        build:
            dockerfile: IdentityServer\Dockerfile
        environment:
            - TZ=Indian/Christmas

    app:
        build:
            dockerfile: App\Dockerfile
        environment:
            - TZ=Indian/Christmas

    api:
        build:
            dockerfile: Api\Dockerfile
        depends_on:
            db:
                condition: service_healthy
        environment:
            - TZ=Indian/Christmas

    # db:
    #     image: mcr.microsoft.com/mssql/server
    #     healthcheck:
    #         test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password0 -Q "SELECT fileid FROM tempdb.sys.sysfiles" -b -o /dev/null
    #         interval: 15s
    #         timeout: 500s
    #         retries: 40
    #     environment:
    #         ACCEPT_EULA: "Y"
    #         MSSQL_SA_PASSWORD: Password0

    db:
        image: postgres
        healthcheck:
            test: pg_isready -U postgres
            interval: 15s
            timeout: 500s
            retries: 40
        environment:
            POSTGRES_PASSWORD: password